### ISSUE TITLE
Where is session variable set?

### ISSUE THREAD

**Issue by melvas6** [nilskj/php-vanilla-htmx#1]
Hi
This is a nice template. 

I saw this line in index.php. What is this for? Where is the session global set?

`$hxRequest = isset($_SERVER['HTTP_HX_REQUEST']) && $_SERVER['HTTP_HX_REQUEST'] == 'true';`

Thanks

**Comment by nilskj** [comment]
Hello! Thanks! It is set on the http header to determine if incoming request is from htmx or browser request. When HTMX is requesting (with hx-get etc) it will add request header `HX-Request` that I parse into this variable as true / false. This enables me to route to different partials at first fetch, compared to subsequent requests from htmx.

**Comment by melvas6** [comment]
Thank you so much
